name: 02 - Jobs and Triggers Practice

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:

  job1:
    name: Job 1 - First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Job 1 is running"

      - name: Step 2
        run: |
          echo "Job 1 completed"

  job2:
    name: Job 2 - Depends on Job 1
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: |
          echo "Job 2 is running after Job 1"

      - name: Step 2
        run: |
          echo "Job 2 completed"

  job3:
    name: Job 3 - Parallel Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Job 3 is running independently"

      - name: Step 2
        run: |
          echo "Job 3 completed"
