name: Secrets Practice

on:
  workflow_dispatch:

jobs:
  use-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Access secret
        run: |
          echo "Using the secret now..."

      - name: Step 2 - Print masked secret (GitHub will hide it)
        run: |
          echo "Your secret is:${{ secrets.MY_SECRET }}"

      - name: Step 3 - Use secret as environment variable
        env:
          LOCAL_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Local secret ENV is also masked:$LOCAL_SECRET"

