name: Variables-and-Data-Flow-Practice

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_value: ${{ steps.set_output.outputs.my_value }}
    steps:
      - id: set_output
        run: echo "my_value=99" >> $GITHUB_OUTPUT
      - name: Show Step Output
        run: echo "Job1 step output: ${{ steps.set_output.outputs.my_value }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Show Job Output
        run: echo "Job2 received output from Job1: ${{ needs.job1.outputs.my_value }}"
